---
#
# YAML configuration file for infer.py
#

# the random seed, for reproducibility
# set to null for no random seed
seed: 42
# the size of each batch of images when performing prediction
batch_size: 32
# the path to the directory of the dataset
dataset: '../resources/plant_dataset_209.h5'

# the path to the root directory used to store experiments
xp_rootdir: 'experiments/'
# the name of log directory for an experiment (result of training)
# you can set to 'last' to refer to the lastly created directory under in <xp_rootdir>
#xp_name:
##parser.add_argument("--eval_all_checkpoints", action="store_true", help="Evaluate all checkpoints starting with the same prefix as model_name ending and ending with step number")