# YAML configuration file for run_inference.py

# the random seed, for reproducibility (set to null for no random seed)
seed: 42

# the type of classification  ['disease', 'plant', 'healthy', 'gen_disease']
class_type: 'disease'
# the size of each batch of images when performing prediction
batch_size: 32

wandb: False

# Option to used mixed precision, be sur that your GPU will not benefit from this -> (compute capability > 6)
fp16: False

# the path to the root directory of our trained models
# "resources/best_models/{model_type}" where model_type can be either of
# 'cnn', 'lab', 'transformers', 'keras_transformers'
# For 'transformers', evaluate models one by one
#      -> use resources/best_models/{model_type}/{model}
xp_dir: 'resources/best_models/keras_transformers'

# the path to the root directory used to store our evaluations
output_dir: 'inference/eval_best_models'
