# YAML configuration file for run_inference.py

# the random seed, for reproducibility (set to null for no random seed)
seed: 42

# the type of classification  ['disease', 'plant', 'healthy', 'gen_disease']
class_type: 'disease'
# the size of each batch of images when performing prediction
batch_size: 32

wandb: False

# the path to the root directory used to store experiments
xp_dir: 'resources/best_models/cnn/224'
#xp_dir: 'resources/best_models/transformers/vit'

#output_dir: 'inference/eval_best_models'
output_dir: 'inference/test'
