# YAML configuration file for run_training.py

# the random seed, for reproducibility
seed: 42

# Images shape
input_shape: [224, 224, 3]

# the type of classification we want to implement
# ['disease', 'plant', 'healthy', 'gen_disease']
class_type: 'disease'

# careful not to use a too large batch size, might lead to OOM errors
batch_size: 32
n_epochs: 20
optimizer: 'adam'
learning_rate: 0.001
lr_decay_rate: 0.1

# Option to use class weights for imbalanced dataset
class_weights: True
# Option to use PolyLoss as loss function
polyloss: False
# Option to compute advanced metrics while training multiple models
eval_during_training: False
# Models to train
models: ["lab_two_path_inception_v3", "lab_two_path_inceptionresnet_v2"]

# Option to use wandb for logging
wandb: True
# Option to overwrite the content of the output directory
overwrite_output_dir: True

# the path to the directory of the dataset
dataset: 'resources/datasets/augm_lab_disease_60343_ds_224.h5'
feature_extractor: 'vit'
# Option to use pipeline for transformers
transformer: False

# Output directory where the model checkpoints will be written
output_dir: 'experiments/cnn-comp'

mean_arr: [118.94, 124.72, 104.59]
std_arr: [49.35, 42.97, 54.13]
augm_mean_arr: [118.14, 124.61, 104.01]
augm_std_arr: [49.30, 42.62, 54.95]
augmlab_mean_arr: [129.75, 122.14, 138.48]
augmlab_std_arr: [44.66, 12.08, 15.12]
