wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    framework: huggingface
    huggingface_version: 4.20.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: val_loss
      6:
      - 3
      7:
      - 1
    - 1: val_f1_m
      6:
      - 3
      7:
      - 2
    python_version: 3.8.12
    start_time: 1659714643
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 2
      - 3
      - 7
      - 8
      - 13
      - 16
      4: 3.8.12
      5: 0.12.19
      6: 4.20.1
      8:
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 32
class_type:
  desc: null
  value: disease
dataset:
  desc: null
  value: ../resources/datasets/augmentation/augm_disease_60343_ds_128.h5
learning_rate:
  desc: null
  value: 0.001
loss:
  desc: null
  value: custom_loss.poly1_cross_entropy_label_smooth
n_train_steps:
  desc: null
  value: 26400
nbr_classes:
  desc: null
  value: 38
nbr_train_batch:
  desc: null
  value: 1320
nbr_train_epochs:
  desc: null
  value: 20
num_log_batches:
  desc: null
  value: 1
optimizer:
  desc: null
  value: adam
train_set_len:
  desc: null
  value: 42240
valid_set_len:
  desc: null
  value: 9051
